add action

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -11,6 +11,10 @@ jobs:
       contents: write # to push chart release and create a release (helm/chart-releaser-action)
 
     runs-on: ubuntu-latest
+    outputs:
+      changed_charts: ${{ steps.chart-releaser.outputs.changed_charts }}
+      chart_version: ${{ steps.chart-releaser.outputs.chart_version }}
+
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
@@ -20,14 +24,15 @@ jobs:
       - name: Configure Git
         run: |
           git config user.name "$GITHUB_ACTOR"
-          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"  
+          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
       - name: Set up Helm
-        uses: azure/setup-helm@v3.5
+        uses: azure/setup-helm@v4
         with:
           version: v3.9.2
 
       - name: Run chart-releaser
-        uses: helm/chart-releaser-action@v1.5.0
+        uses: helm/chart-releaser-action@v1
+        id: chart-releaser
         env:
           CR_TOKEN: "${{ github.token }}"
 
@@ -37,28 +42,47 @@ jobs:
       contents: write  # Needed to commit the generated file
     needs: 
       - release
+    if: needs.release.outputs.changed_charts != ''
     steps:
       - uses: actions/checkout@v4
         with:
           ref: gh-pages
           fetch-depth: 0
 
-      - name: debug-print
-        run: |
-          echo "Current directory is $(pwd)"
-          echo "Contents of the directory are $(ls -la)"
-          echo "Contents of the directory are $(ls -la /home/runner/work/helm-release/helm-release/)"
-
       - name: Generate Helm Charts HTML
         uses: ./.github/actions/generate-helm-html-index
         with:
-          index-file: 'index.yaml'
-          output-file: 'index.html'
+          index_file: 'index.yaml'
+          output_file: 'index.html'
       
       - name: Commit and Push
         run: |
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
+          git config --local user.email "$GITHUB_ACTOR"
+          git config --local user.name "$GITHUB_ACTOR@users.noreply.github.com"
           git add index.html
-          git commit -m "Update Helm charts page" || exit 0  # Don't fail if no changes
+          git commit -m "Update Helm charts page version: ${{ needs.release.outputs.changed_charts  }}" || exit 0  # Don't fail if no changes
           git push
+
+  deploy:
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    runs-on: ubuntu-latest
+    permissions:
+      id-token: write  # Needed to deploy to GitHub Pages
+      pages: write
+    needs:
+      - generate-page
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Setup Pages
+        uses: actions/configure-pages@v5
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v3
+        with:
+          # Upload entire repository
+          path: '.'
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v4
